version: "2.1"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: 'timeout 2 bash -c "</dev/tcp/localhost/27017"'
      interval: 5s
      timeout: 5s
      retries: 10

  postgres:
    container_name: postgres
    image: postgres
    env_file: '.env'
    restart: always
    ports:
      - "5432:5432"

  mysql:
    container_name: mysql
    image: mysql:5
    env_file: '.env'
    restart: always
    ports:
      - "3306:3306"

volumes:
  mongodata:
